# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:
  push:
    branches:
      master
    tags:
      - '*'

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: lint
        run: yarn lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: yarn install
        run: yarn --frozen-lockfile --install
      - name: test
        run: yarn test
